### ISSUE TITLE
Does not launch in VSCodium - missing dist/index.html

### ISSUE THREAD

**Issue by Beep6581** [pcislo/vscode-nuget-gallery#100]
NuGet Gallery 0.0.24 does not work in [VSCodium](https://vscodium.com/) 1.76.0 in Manjaro.

Steps to reproduce:
1. Fire up VSCodium and install NuGet Gallery. It seems to install correctly.
2. Restart VSCodium, just to be sure.
3. Run the Command Pallet and "Open NuGet Gallery"

```
Command 'NuGet: Open NuGet Gallery' resulted in an error

A system error occurred (ENOENT: no such file or directory, open '/home/me/.vscode-oss/extensions/patcx.vscode-nuget-gallery-0.0.24-universal/web/dist/index.html')
```

Indeed the `dist` folder does not exist.

```
ls -Ggah ~/.vscode-oss/extensions/patcx.vscode-nuget-gallery-0.0.24-universal/web/                                                           ✔ 
total 28K
drwxr-xr-x 4 4,0K 20 mar 19.53 .
drwxr-xr-x 6 4,0K 20 mar 19.53 ..
-rw-r--r-- 1  214 20 mar 19.53 .gitignore
-rw-r--r-- 1 1,3K 20 mar 19.53 package.json
drwxr-xr-x 2 4,0K 20 mar 19.53 public
-rw-r--r-- 1  375 20 mar 19.53 README.md
drwxr-xr-x 3 4,0K 20 mar 19.53 src
```

**Comment by pcislo** [comment]
The extension has neved been tested on VSCodium, so I don't guarantee it will work.

**Comment by Beep6581** [comment]
@pcislo VSCodium is VSCode without the added MS telemetry. If it works in one, it should work in the other. Are you not interested at all in even looking into this?
