### ISSUE TITLE
Error load package metadata and backward version sorting

### ISSUE THREAD

**Issue by plctremblay** [pcislo/vscode-nuget-gallery#101]
Hi, 

I am loading packages from a custom source (https://nuget.optimizely.com/feed/packages.svc/). This source works as expected in VS NPM but with the extension, I am unable to see the metadata. Only a "Error load package metadata" on all packages.

Let me know if there's any fix or it's something specific with this source that may not be compatible with the extension and if it could be fixed.

In addition, versions from this source show in reversed order in the extension. The oldest is selected by default and at the top.

Thank you,
Pier-Luc

**Comment by pcislo** [comment]
You can run _Developer Tools_ in visual code to debug the request and see the response. Probably there are some issues with CORS.
