### ISSUE TITLE
can't open Nuget Gallery in VSCodium (complains about no finding index.html)

### ISSUE THREAD

**Issue by Draugor** [pcislo/vscode-nuget-gallery#102]
Hello, 

i installed NuGet Gallery in VSCodium but when i tried to open it via the command or per right-click on a csproj-file i would get the error:
![grafik](https://github.com/pcislo/vscode-nuget-gallery/assets/6240419/fc58bed7-0d41-4037-967e-e9cc8032e5f5)

after some experimentation, i installed VSCode and tested it there, and it worked. 
So looking at the extensions directories and comparing them, it seems the open-vsc extension is missing the "../web/dist/" folder so i could fix that by copying it over, still wanted to let you know :)

kind regards

**Comment by sjsepan3** [comment]
I have an error that seems related, at least by the path involved.
However, I get it with the Code OSS pkg on GhostBSD.

Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-28T17:39:24.159Z
Electron: 22.3.17
ElectronBuildId: undefined
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: FreeBSD x64 13.2-STABLE

The path it is looking for in the error message is... 
`/home/sjsepan/.vscode-oss/extensions/patcx.vscode-nuget-gallery-0.0.24-universal/web/dists/index.html`
...and the path that I have on my system is...
`/home/sjsepan/.vscode-oss/extensions/patcx.vscode-nuget-gallery-0.0.24-universal/web/public/index.html`

![Screenshot at 2023-08-21 01-06-46](https://github.com/pcislo/vscode-nuget-gallery/assets/121126599/34753502-d902-4761-93e1-e8ca32b269aa)
![Screenshot at 2023-08-21 11-23-54](https://github.com/pcislo/vscode-nuget-gallery/assets/121126599/8889eee5-74a6-4b5a-a458-6b4736fd28bc)
