### ISSUE TITLE
[Feature Request] Package Description Window

### ISSUE THREAD

**Issue by igoforth** [pcislo/vscode-nuget-gallery#115]
Hi!

The recent changes to the NuGet Gallery Extension is really neat and I like the direction its headed. One feature I really liked about the old GUI was the ability to see package descriptions and version information. And, if I wanted to learn more, it provided a direct link to the package page. I'm really missing that in the latest version.

Is there a plan to bring that info back?

Thanks!

**Comment by pcislo** [comment]
Hi, thanks for feedback. I will add it in forthcoming days.

**Comment by pcislo** [comment]
I've added package information, let me know if you have any feedback otherwise I will close this issue.
