### ISSUE TITLE
Don't remove 'Open NuGet Gallery'

### ISSUE THREAD

**Issue by yedajiang44** [pcislo/vscode-nuget-gallery#116]
New version viewer too little information displayed. 

And it should not be displayed in the panel, which is very unfriendly to multi-language developers. The panel should display universal tabs, the most important thing is that the display space is limited. what do you think?

**Comment by pcislo** [comment]
I will add more information about the package on the panel. 

Panel can be easily configured and you can switch off tabs that are not needed, however I will consider adding this webview page as an additional option as in the previous version.

**Comment by yedajiang44** [comment]
> 我将在面板上添加有关该包的更多信息。
> 
> 面板可以轻松配置，您可以关闭不需要的选项卡，但是我会考虑像以前的版本一样添加此 webview 页面作为附加选项。
Thank you for your reply. I am looking forward to the release of the new version. In addition, I am surprised that the repositorie  has not changed for many years has been updated recently. Thank you again for your efforts.

**Comment by pcislo** [comment]
I've added package information, let me know if you have any feedback otherwise I will close this issue.

**Comment by yedajiang44** [comment]
> I've added package information, let me know if you have any feedback otherwise I will close this issue.

nice! I see it and it's great and thanks for the effort~

also, how to update packages in all projects

**Comment by pcislo** [comment]
> also, how to update packages in all projects

right now it's not possible, but I've added feature request #119  for that and will try to implement it soon

**Comment by yedajiang44** [comment]
cool~ I close this iss and follw #119 

thanks!
