### ISSUE TITLE
Install NET SDK 8.0.200 or higher to access NuGet commands

### ISSUE THREAD

**Issue by AndresGMD** [pcislo/vscode-nuget-gallery#117]
Currently I have:  

#_Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631_

Extensions version:

- NuGet Gallery v1.0.0
- C# v2.28.11
- C# Dev Kit v1.5.20

I've already installed dotnet SDK 8.0.300

Inside my project I've already update Global.json

```JSON
{
    "sdk": {
        "version": "8.0.300"
    }
}
```

Run the following command `dotnet --version` **result** `8.0.300`

Steps to reproduce:

1. Ctrl+Shift+P to open Command Palette
2. Run command: >NuGet: Add NuGet Package...

Finally I get the message:

![image](https://github.com/pcislo/vscode-nuget-gallery/assets/90065355/17900457-194e-40db-a200-548f5a4b8585)

Thanks in advance!

**Comment by pcislo** [comment]
There is no command "NuGet: Add NuGet Package" in this extension. Use "NuGet: Focus on NuGet View"

**Comment by AndresGMD** [comment]
Thanks @pcislo 

Yeah it works!
