### ISSUE TITLE
Error on initial load - no packages visible.

### ISSUE THREAD

**Issue by zuc704** [pcislo/vscode-nuget-gallery#12]
Upon installing the extension and launching "Nuget: Open Gallery" from the command palette, a new tab opens, with the message "error."

- All other extensions disabled
- Using latest version of VS Code (1.41.1)
- Typing in the "search/filter" bar displays a loading icon in place of "error" for a half second, then "error" reappears.

![image](https://user-images.githubusercontent.com/7771894/71546522-bb5b9b00-2965-11ea-9435-cc834b31888d.png)

**Comment by pcislo** [comment]
Could you open "Webview Developer Tools" from the command pallette and send me the content of the error shown in the console and the response from the server from the "https://azuresearch-usnc.nuget.org/query..." ?

**Comment by Smoovsky** [comment]
> Could you open "Webview Developer Tools" from the command pallette and send me the content of the error shown in the console and the response from the server from the "https://azuresearch-usnc.nuget.org/query..." ?

Same problem here.

But after running open Webview Developer Tools from command pallette, nothing happened. I tried on two computers, both show nothing.

**Comment by zuc704** [comment]
Hi, the following is all I'm getting after running webview dev tools:

[console-1577652548902.log](https://github.com/pcislo/vscode-nuget-gallery/files/4008557/console-1577652548902.log)
[console-1577652533247.log](https://github.com/pcislo/vscode-nuget-gallery/files/4008558/console-1577652533247.log)
[console-1577653814694.log](https://github.com/pcislo/vscode-nuget-gallery/files/4008572/console-1577653814694.log)


Nothing I'm doing after loading the extension seems to cause anything else to show in console, but I ran the debugger and I'm seeing the following in transformResponse which is causing an issue in the "createQuery" function, which then seems to be returning "error":

`SyntaxError: Unexpected token R in JSON at position 0`

Stacktrace below:

c.transformResponse (VM110:formatted:441)
(anonymous) (VM110:formatted:11360)
x (VM110:formatted:11426)
t.exports (VM110:formatted:11359)
(anonymous) (VM110:formatted:9642)
Promise.then (async)
t.exports (VM110:formatted:9640)
Promise.then (async)
c.request (VM110:formatted:209)
r.forEach.c.<computed> (VM110:formatted:220)
(anonymous) (VM110:formatted:372)
(anonymous) (VM110:formatted:10381)
createQuery (VM110:formatted:10380)
refresh (VM110:formatted:10430)
refreshList (VM110:formatted:10525)
v (VM110:formatted:7773)
b (VM110:formatted:7800)
m (VM110:formatted:7795)
setTimeout (async)
ku (VM110:formatted:7066)
g (VM110:formatted:7778)
k (VM110:formatted:7819)
updateFilter (VM110:formatted:10557)
filterChanged (VM110:formatted:9913)
ne (VM110:formatted:1254)
n (VM110:formatted:1384)
ne (VM110:formatted:1254)
t.$emit (VM110:formatted:2140)
input (VM110:formatted:9964)
ne (VM110:formatted:1254)
n (VM110:formatted:1384)
Qi.o._wrapper (VM110:formatted:3521)

**Comment by Smoovsky** [comment]
> Could you open "Webview Developer Tools" from the command pallette and send me the content of the error shown in the console and the response from the server from the "https://azuresearch-usnc.nuget.org/query..." ?

I assume this response is causing the problem:
![image](https://user-images.githubusercontent.com/34542126/71567894-b12cce80-2b16-11ea-976d-213ca2a61664.png)

**Comment by pcislo** [comment]
There was an error in the default configuration. The official nuget feed url was wrong. It should be "https://api.nuget.org/v3/index.json". I've fixed it in 0.0.6 release, but the url can be also changed in the configuration for the previous release (0.0.5).
