### ISSUE TITLE
Private Feed packages not loading in Nuget Gallery

### ISSUE THREAD

**Issue by saikrishna-dev** [pcislo/vscode-nuget-gallery#121]
As the title says looks like the private packages from private feed are not loading, It used to work but noticed this issue today not sure from when. I can confirm the feed is working as it works just fine in Visual Studio. The extension just gets stuck loading infinitely.
![image](https://github.com/pcislo/vscode-nuget-gallery/assets/60167278/721918fd-20ed-4b6f-a44f-8330a70aaa0d)

**Comment by pcislo** [comment]
Does the problem still exists on the newest version?

**Comment by goors** [comment]
Here as well.

**Comment by saikrishna-dev** [comment]
I will test the latest version tomorrow, and thanks regarding the typo haha.

**Comment by saikrishna-dev** [comment]
Hey @pcislo The extension seems to work for me now, Thank you :)
