### ISSUE TITLE
support open in csproj /sln just like vs 2022

### ISSUE THREAD

**Issue by heartacker** [pcislo/vscode-nuget-gallery#122]
,that is use full

**Comment by pcislo** [comment]
please provide more information, why this can be better that current solution

**Comment by heartacker** [comment]
hi, thank you for repley

there is the question
1. I cannot know what nugets I have installed now 

![image](https://github.com/user-attachments/assets/e0beab5e-d044-4442-bf11-28c864ff61ba)

2. I want to what I have installed， where is some updates, I can not know


3. if there are multi csporject,  how can I see specify cs project nugets status

5. Have can I update the same nuget package if there are multi project and have same nuget installed, we must update it as the same time


maybe vs 2022 is good example

![image](https://github.com/user-attachments/assets/85ff0190-8174-4588-a3bb-bbf85b1a909d)

we can open a sln/cs proj
and see what happens(install/update/multi project)

**Comment by pcislo** [comment]
Listing installed packages will be added in the next version. It will solve most of the problems that you mentioned. 
In case of updating packages in multiple projects and the same time, it's possible in the current version. Just use the plus button next to the projects that you want to update/

![scr](https://github.com/user-attachments/assets/b5bd8d1f-699a-49cc-ac61-5b2375ad20f8)
