### ISSUE TITLE
Path to shell executable does not exist

### ISSUE THREAD

**Issue by JoshHariz** [pcislo/vscode-nuget-gallery#124]
I am trying to configure the credential provider for a private repository. I have downloaded the credential provider and can confirm that it exists. When I copy the path into file explorer it works fine. 

For some reason your task seems to be concatenating my workspace folder and the credentialProvider path. I kept the default credential path and received the following errors. 

Credential Provider folder setting: {user-profile}/.nuget/plugins/netcore/CredentialProvider.Microsoft

Errors:

Executing task: C:\Users\JoshH\source\repos\hip-core-container-registry\"C:\Users\JoshH\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe" -C False -R -U **privateUrl**

 *  The terminal process failed to launch: Path to shell executable "C:\Users\JoshH\source\repos\hip-core-container-registry\"C:\Users\JoshH\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe"" does not exist. 
 
 I then tried to escape the workspace directory and essentially hack it using the following path:
 
 ..\\..\\..\\..\\..\\.nuget\plugins\netcore\CredentialProvider.Microsoft
 
 But it still broke with the following messages:
 
 Executing task: C:\Users\JoshH\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe" -C False -R -U **privateUrl**

 *  The terminal process failed to launch: Path to shell executable "C:\Users\JoshH\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe"" does not exist. 
 
 I can guarantee that the credential provider is installed and is accessible at that path, however the extension is making the path invalid no matter what I do.
 
 Are you able to assist with this?

**Comment by pcislo** [comment]
I will check it and will be back with the answer.

**Comment by pcislo** [comment]
@JoshHariz please check the 1.1.1 version and let me know if the problem still exists.

**Comment by JoshHariz** [comment]
@pcislo Thank you very much, the new update has resolved the issue!

**Comment by Dennis-GDR** [comment]
Same problem here with Version 1.2.2 on MacOS if this is important.

"The terminal process failed to launch: Path to shell executable "dotnet "/Users/cddev/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll"" does not exist."
