### ISSUE TITLE
Unable to install package due to line break

### ISSUE THREAD

**Issue by savitskiy-danylo** [pcislo/vscode-nuget-gallery#130]
Hi!

This problem occured a few weeks ago. When I try to install any package to the project, nuget gallery stucks on loading.
 
![image](https://github.com/user-attachments/assets/20f411ac-0192-4a17-a559-46b457701725)

I checked terminal and saw this:
![image](https://github.com/user-attachments/assets/7be01b72-4c39-463e-bd06-dc5c6262c910)
_*There is a syntax error in the file name, folder name, or volume label._

As you can see from screenshot, nuget gallery breaks line and because of that package cannot be installed. If I try just copy and paste command, everything works (breaks are not copied to clipboard).

I didn't find how to solve this problem either on github or google.
If you need any information, I will be happy to provide it to you.

Thank you.

**Comment by pcislo** [comment]
Does it happen for every project?
