### ISSUE TITLE
Icon for workbench panel

### ISSUE THREAD

**Issue by eimantas** [pcislo/vscode-nuget-gallery#135]
VS Code introduced a setting that allows to change the labels in workbench panel to icons. This extension has no icon displayed

<img width="461" alt="NuGet Gallery tab without icon" src="https://github.com/user-attachments/assets/9560659b-13ed-4f52-817f-ccb2f46b042e">

**Comment by pcislo** [comment]
Thanks to @pvlzh it will be released soon.

**Comment by eimantas** [comment]
Thanks a heap! Looking forward to the release :)
