### ISSUE TITLE
Unable to display and obtain higher version numbers

### ISSUE THREAD

**Issue by alook123** [pcislo/vscode-nuget-gallery#138]
![CleanShot 2024-11-19 at 16 52 23@2x](https://github.com/user-attachments/assets/0ed4b75d-edd7-4564-920f-9c881224a1fb)

The current highest version number of the nuget package is 0.0.1.3065. But it is not displayed, and the latest version of the nuget package cannot be updated. And the version number is sorted incorrectly

**Comment by pcislo** [comment]
duplicated https://github.com/pcislo/vscode-nuget-gallery/issues/136
