### ISSUE TITLE
No feedback on what it is doing

### ISSUE THREAD

**Issue by arcotek-ltd** [pcislo/vscode-nuget-gallery#15]
I am not sure if the extension is working or not. I've tried to install `Microsoft.Windows.Compatibility`.

I find the package and click *install*. The Install button gets a little orange box around it, but nothing else happens. Am I waiting for it to download, or is it not working?

It would be very helpful if we could have some feedback of the progress.

T.I.A.

**Comment by arcotek-ltd** [comment]
According to a screenshot of your app on SO: https://stackoverflow.com/questions/40675162/install-a-nuget-package-in-visual-studio-code, there should be a selection box to choose the `.csproj` file.

**Comment by pcislo** [comment]
In order to install selected package you need to tick the checkbox next to a project in the selection box on the right. If your project is not listed, maybe it's structure is not valid - if possible, please upload your `.csproj` and i will take a look.

**Comment by rkramer1964** [comment]
I am having the same issue.  One of the problematic csproj is attached
[bluepaysvc.zip](https://github.com/pcislo/vscode-nuget-gallery/files/4293178/bluepaysvc.zip)

**Comment by pcislo** [comment]
I can't reproduce this issue. I've opened your csproj and it's fine - the project is listed on the right side. Have you tried using refresh button? 

![obraz](https://user-images.githubusercontent.com/4640882/76007350-32855080-5f0e-11ea-9282-8233621a355b.png)

**Comment by rkramer1964** [comment]
Yes - the refresh button causes the "dots" animation to appear and  
it continues to show the dots for over 10 minutes without displaying  
any csproj.  Is it scanning the entire disk, or can you tell me what  
folder it is scanning through?

Quoting Patryk Cisło <notifications@github.com>:

> I can't reproduce this issue. I've opened your csproj and it's fine  
> - the project is listed on the right side. Have you tried using  
> refresh button?
>
>   [1]
>
>   —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub[2], or unsubscribe[3].



Links:
------
[1]  
https://user-images.githubusercontent.com/4640882/76007350-32855080-5f0e-11ea-9282-8233621a355b.png
[2]  
https://github.com/pcislo/vscode-nuget-gallery/issues/15?email_source=notifications&email_token=AGNY7XWPXY72UUKWLVF23VDRF7N7FA5CNFSM4LARVO62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEN6E5FY#issuecomment-595349143
[3]

**Comment by pcislo** [comment]
It's scanning only the folder that is opened in vs code. Refreshing should take less then a second. 

Could you open the developer console and check if there are any errors there? `Help`->`Toggle Developer Tools` and run command "`Developer: Open Webview Developer Tools`". Please check both consoles.

Moreover you can try to move your csproj file to a folder where no administrator permissions are required. Maybe there is a problem with listing files in the folder.

**Comment by rkramer1964** [comment]
I'll have to try that later tonight after I get off of work

Quoting Patryk Cisło <notifications@github.com>:

> It's scanning only the folder that is opened in vs code. Refreshing  
> should take less then a second.
>
>   Could you open the developer console and check if there are any  
> errors there? Help->Toggle Developer Tools and run command  
> "Developer: Open Webview Developer Tools". Please check both consoles.
>
>   Moreover you can try to move your csproj file to a folder where no  
> administrator permissions are required. Maybe there is a problem  
> with listing files in the folder.
>
>   —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub[1], or unsubscribe[2].



Links:
------
[1]  
https://github.com/pcislo/vscode-nuget-gallery/issues/15?email_source=notifications&email_token=AGNY7XRAR5BK5QSLR7PN253RF7QRRA5CNFSM4LARVO62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEN6HLMI#issuecomment-595359153
[2]

**Comment by MosesMachua** [comment]
Hi @pcislo. I took a screenshot of the error thrown when Nuget Gallery loads. It appears to be an undefined object. See below

![Nuget galley error](https://user-images.githubusercontent.com/19628623/76131548-e523e480-5fdc-11ea-8bf7-bbd4b850ee65.png)

Below is the function throwing the error in `extension.js`

![Nuget galley error_function](https://user-images.githubusercontent.com/19628623/76131730-acd0d600-5fdd-11ea-9bcd-488b4b5246f4.png)


Another issue I noticed is Nuget Gallery will sometimes fail to load. Below is the screenshot of the error when that happens

![Nuget galley error_load](https://user-images.githubusercontent.com/19628623/76131103-3206bb80-5fdb-11ea-837d-eb591ac511db.png)

**Comment by pcislo** [comment]
> 
> 
> Hi @pcislo. I took a screenshot of the error thrown when Nuget Gallery loads. It appears to be an undefined object. See below
> 
> ![Nuget galley error](https://user-images.githubusercontent.com/19628623/76131548-e523e480-5fdc-11ea-8bf7-bbd4b850ee65.png)
> 
> Below is the function throwing the error in `extension.js`
> 
> ![Nuget galley error_function](https://user-images.githubusercontent.com/19628623/76131730-acd0d600-5fdd-11ea-9bcd-488b4b5246f4.png)
> 
> Another issue I noticed is Nuget Gallery will sometimes fail to load. Below is the screenshot of the error when that happens
> 
> ![Nuget galley error_load](https://user-images.githubusercontent.com/19628623/76131103-3206bb80-5fdb-11ea-837d-eb591ac511db.png)

Could you attach your `.csproj` for which the error occured, please?

**Comment by MosesMachua** [comment]
Here's the `.csproj` file.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
    <IsPackable>false</IsPackable>
    <SpaRoot>ClientApp\</SpaRoot>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(SpaRoot)node_modules\**</DefaultItemExcludes>

    <!-- Set this to true if you enable server-side prerendering -->
    <BuildServerSideRenderer>false</BuildServerSideRenderer>
    <Description>ASPNET Core 2.2 - Angular8 startup template for Quick Application Development</Description>
    <Copyright>Copyright © 2019 www.ebenmonney.com</Copyright>
    <PackageProjectUrl>https://www.ebenmonney.com/quickapp</PackageProjectUrl>
    <Company>EBENMONNEY</Company>
    <Version>2.8.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="8.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="6.1.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="8.4.0" />
    <PackageReference Include="IdentityServer4" Version="2.5.0" />
    <PackageReference Include="IdentityServer4.AccessTokenValidation" Version="2.7.0" />
    <PackageReference Include="IdentityServer4.AspNetIdentity" Version="2.5.0" />
    <PackageReference Include="MailKit" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="Serilog.Extensions.Logging.File" Version="2.0.0-dev-00024" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DAL\DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ClientApp\dist\**" />
    <Compile Remove="Logs\**" />
    <!-- Don't publish the SPA source files, but do show them in the project files list -->
    <Content Remove="$(SpaRoot)**" />
    <Content Remove="ClientApp\dist\**" />
    <Content Remove="Logs\**" />
    <None Remove="$(SpaRoot)**" />
    <None Include="$(SpaRoot)**" Exclude="$(SpaRoot)node_modules\**" />
  </ItemGroup>

  <ItemGroup>
    <!--Include email templates in the publish output-->
    <Content Include="Helpers\Templates\*.template" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="ClientApp\dist\**" />
    <EmbeddedResource Remove="Logs\**" />
    <None Remove="ClientApp\dist\**" />
    <None Remove="Logs\**" />
  </ItemGroup>

  <Target Name="DebugEnsureNodeEnv" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And !Exists('$(SpaRoot)node_modules') ">
    <!-- Ensure Node.js is installed -->
    <Exec Command="node --version" ContinueOnError="true">
      <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
    <Message Importance="high" Text="Restoring dependencies using 'npm'. This may take several minutes..." />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
  </Target>

  <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    <!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build -- --prod" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build:ssr -- --prod" Condition=" '$(BuildServerSideRenderer)' == 'true' " />

    <!-- Include the newly-built files in the publish output -->
    <ItemGroup>
      <DistFiles Include="$(SpaRoot)dist\**; $(SpaRoot)dist-server\**" />
      <DistFiles Include="$(SpaRoot)node_modules\**" Condition="'$(BuildServerSideRenderer)' == 'true'" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>%(DistFiles.Identity)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>
</Project>
```

It's [emonney's](https://github.com/emonney) Asp.net Angular startup template. You can clone the application at
https://github.com/emonney/QuickApp

**Comment by pcislo** [comment]
I see, there is a problem caused by `Microsoft.AspNetCore.App` package - there is no version specified for this `.csproj`

**Comment by MosesMachua** [comment]
I can confirm that when I remove the line

`<PackageReference Include="Microsoft.AspNetCore.App" />`

 the `.csproj` checkbox is properly displayed and packages can be installed. The problem is lack of version like you said. Thanks
