### ISSUE TITLE
This is awesome! Some suggestions

### ISSUE THREAD

**Issue by JohnGalt1717** [pcislo/vscode-nuget-gallery#20]
This is a great start for something that's desperately needed!

1. If possible, it should just scan the entire folder structure looking for a nuget.config file and use all of the sources there with the credentials in the file. It should also search the central location that vs.net uses as well on the machine. (and allow the user to add new ones and choose either a local nuget or the central location.
2. Need an Update tab desperately.   Both an option for the entire solution, (i.e. the one selected by omnisharp currently) or on a specific project. 
3. In the same vein as #2, it would be nice to have a right click on .csproj that would bring up the nuget for that project with install, updates, and new for that project. Right clicking on an sln would bring up the solution wide version of the same.

Awesome work! Can't wait to see what this becomes!  This is literally the last reason we have VS.net on our machines.

**Comment by pcislo** [comment]
Thanks for your feedback. I will think it over and try to apply as many suggested changes as possible in the coming release.

**Comment by pcislo** [comment]
Some of the suggestions will be implemented:  #32 #33
