### ISSUE TITLE
Error while adding package 'Package name' to project 'e:/path/to/project.csproj'. The project does not support adding package references through the add package command

### ISSUE THREAD

**Issue by ssoher** [pcislo/vscode-nuget-gallery#23]
I get a `Error while adding package 'Package name' to project 'e:/path/to/project.csproj'. The project does not support adding package references through the add package command`
for every project in my solution.

**Comment by pcislo** [comment]
What is the target framework of your projects?

**Comment by ssoher** [comment]
It's 4.7.1, the projects are generated by the Unity game engine if it's of any relevancy.

**Comment by pcislo** [comment]
I think that's why it's not working. The command used by extension (`dotnet add package`) works only with .NET Core apps.
