### ISSUE TITLE
Enable Prerelease Versions

### ISSUE THREAD

**Issue by luchomejia** [pcislo/vscode-nuget-gallery#25]
As of now, there is no way to include prerelease versions in the versions dropdwon.
Some nugget packages have alpha, beta versions that are not yet stable versions but you may want to install them as they might solve certain bugs.
In visual studio the nuge package manager has a checkbox to "include prerelease".
It would be nice if the same functionality gets added to the extension.

**Comment by pcislo** [comment]
Hi, thanks for your feedback. I've added it in 0.0.11 release.

**Comment by pcislo** [comment]
There are some issues when publishing new version. I will publish changes as soon as I figure it out.

**Comment by pcislo** [comment]
Added in 0.0.19 release
