### ISSUE TITLE
Install button is disabled

### ISSUE THREAD

**Issue by eric-saintetienne** [pcislo/vscode-nuget-gallery#29]
Hi,

On Fedora 31 64-bit I've installed `code` and followed instruction on Microsoft website to install .Net core 3.1:
```
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo wget -O /etc/yum.repos.d/microsoft-prod.repo https://packages.microsoft.com/config/fedora/31/prod.repo
```
then:
```
sudo dnf install aspnetcore-runtime-3.1
sudo dnf install dotnet-runtime-3.1
```
Which result in those packages being installed:
```
$ sudo dnf list installed
code.x86_64                                       1.46.1-1592429042.el7                @code                                               
aspnetcore-runtime-3.1.x86_64                     3.1.5-1                              @packages-microsoft-com-prod                        
dotnet-runtime-3.1.x86_64                         3.1.5-1                              @packages-microsoft-com-prod                        
dotnet-runtime-deps-3.1.x86_64                    3.1.5-1                              @packages-microsoft-com-prod                        
```

In VSCode's Extensions I've installed vscode-nuget-gallery v0.0.19 using VSCode built-in extension marketplace.

But when I open the gallery and browse for nuget package, the `Install` button is always disabled. I can't installed any nuget package with the gallery. I suspect it's not due to the gallery but a misconfiguration of sorts but I need help and guidance. What do I miss?

Thank you.

**Comment by pcislo** [comment]
Do you have any project in your workspace? Install button is enabled when at least one project is selected. If you have selected a project and button is still disabled, please provide me some screenshots.

**Comment by snowfrogdev** [comment]
I'm also experiencing this and my workspace contains a .sln file and several C# projects. I don't see a way in the Nuget Gallery UI to select a project.
![image](https://user-images.githubusercontent.com/22530235/191036284-3f556edd-4638-490c-83d4-65412afe49f7.png)

**Comment by pcislo** [comment]
Are these C# projects using .NET Core instead of .NET Framework?

**Comment by snowfrogdev** [comment]
> Are these C# projects using .NET Core instead of .NET Framework?

.NET 6

**Comment by pcislo** [comment]
Send me csproj if possible so I will take a look. It's hard to say why it's not finding it, maybe something is wrong with csproj.
