### ISSUE TITLE
Prerelease versions not showing up.

### ISSUE THREAD

**Issue by jongio** [pcislo/vscode-nuget-gallery#30]
Azure Identity has preview versions, i.e.
https://www.nuget.org/packages/Azure.Identity/1.2.0-preview.4

They don't show up when I search for 'azure.identity', check the prerelease box, and click filter:

![image](https://user-images.githubusercontent.com/2163001/85361580-2c24df80-b4d1-11ea-8720-85fc8ccc9785.png)

azsdke2e

**Comment by pcislo** [comment]
NuGet API is not returning preview versions for this package, despite "isprerelase" flag in the request. I've no idea why.

**Comment by jongio** [comment]
This extension does... https://github.com/jmrog/vscode-nuget-package-manager

Maybe diff the nuget request from that one and yours?

**Comment by pcislo** [comment]
`vscode-nuget-package-manager` extension works a little bit different. It's fetching package names first and the versions in the second request. My extension is using different endpoints and I'm fetching list of packages with all the details at once.

**Comment by jongio** [comment]
Did ya figure it out?

**Comment by pcislo** [comment]
Yes, the new release has been already published.

**Comment by jongio** [comment]
Works!  

Thanks a lot!!!

![image](https://user-images.githubusercontent.com/2163001/85763054-30b3e880-b6c9-11ea-9f8e-9cabf79bd193.png)
