### ISSUE TITLE
Nuget Gallery should show up in Activity Bar

### ISSUE THREAD

**Issue by kiran94** [pcislo/vscode-nuget-gallery#35]
In addition to the opening the gallery via command pallete:  `>Nuget: Open Gallery`, Could we also add an option for the feature to show up in the Activity Bar? 

![image](https://user-images.githubusercontent.com/7103956/87222123-1c2e4c00-c369-11ea-8ed9-ebb98a7c4e14.png)

[vscode-solution-explorer](https://marketplace.visualstudio.com/items?itemName=fernandoescolar.vscode-solution-explorer) are doing some similar, as you can see from my screenshot

**Comment by pcislo** [comment]
Yes, I think it's a good suggestion. I will add it.

**Comment by pcislo** [comment]
I'm afraid that Activity Bar is tightly coupled to TreeView and it cannot be used without it. My first idea was to move projects list to this TreeView, but I'm not sure if there is any profit from that and TreeView API is much more limited.

Do you need that feature to have an easy access to the extension? Do you think that having access to this command in the context menu of the projects will meet your requirements?

**Comment by kiran94** [comment]
Thanks for looking into this. Yes this was purely an ease of access / quality of life enhancement but for now I will just access the extension via Command Palette. 

Feel free to close this issue!

**Comment by pcislo** [comment]
I've added command to context menu in release 0.0.22.
