### ISSUE TITLE
新增自定义Source URL会出现跨域问题

### ISSUE THREAD

**Issue by ElivsXia** [pcislo/vscode-nuget-gallery#40]
新增自定义Source URL会出现跨域问题
[Embedded Page] Access to XMLHttpRequest at 'http://api.nuget.xxx.com/v3/index.json' from origin 'vscode-webview://ac62e103-7ae7-4b26-99da-0acff509a042' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by pcislo** [comment]
add Access-Control-Allow-Origin' header or wait for https://github.com/pcislo/vscode-nuget-gallery/pull/26
