### ISSUE TITLE
Unable to install Nuget Gallery in VS Code 1.36.1

### ISSUE THREAD

**Issue by kds-snyder** [pcislo/vscode-nuget-gallery#41]
I tried to install Nuget Gallery, but received an error message that it is not compatible with VS Code 1.36.1. I don't see any details at https://marketplace.visualstudio.com/items?itemName=patcx.vscode-nuget-gallery on which VS Code versions are compatible with Nuget Gallery.

![image](https://user-images.githubusercontent.com/14143452/88852961-fe604400-d1bc-11ea-80c7-76aec8c107a6.png)

**Comment by pcislo** [comment]
It requires at least 1.37.0 version. I will add this information to extension details.

**Comment by kds-snyder** [comment]
I installed VS Code 1.47.3, and was able to install Nuget Gallery.
