### ISSUE TITLE
Nuget CLI installed.  VSCODE latest installed.  Nuget Gallery installed.  Lists packages but will not enable install

### ISSUE THREAD

**Issue by armplinker** [pcislo/vscode-nuget-gallery#44]
Installed all this, verified nuget.exe cli can install package (newtonsoft.json).  When I open the gallery within VSCode, however, it lists all packages it can find as expected, with version #s, but when I pick one. the install button is never enabled.  I have no clue what to do here... Please advise.

**Comment by pcislo** [comment]
Do you have projects (*.csproj) in your workspace? This extension is not using nuget cli, but `dotnet add package` command

**Comment by armplinker** [comment]
No.  This is the deployed website itself.  I am trying to install its roslyn compiler. 

It is only the  aspx, ascx, ashx, dll, and web.config.  No cs, no csproj.  If I put the csproj in there, will it work?

**Comment by pcislo** [comment]
This extension is adding packages to projects. If you want to make use of it, you need to a project.
