### ISSUE TITLE
Publish to open-vsx.org

### ISSUE THREAD

**Issue by jamsilva** [pcislo/vscode-nuget-gallery#45]
Could you please publish the extension to [open-vsx.org](https://open-vsx.org/)?
There is a [version there](https://open-vsx.org/extension/patcx/vscode-nuget-gallery) that seems to be automatically generated, but because it only compiles the top-level directory (but not web) there is no UI when installed...

**Comment by pcislo** [comment]
open-vsx.org is not supported right now
