### ISSUE TITLE
Show all installed packages?

### ISSUE THREAD

**Issue by shaneparsons** [pcislo/vscode-nuget-gallery#55]
Is there a way to show all currently installed packages? If not, is this something you foresee being able to add?

**Comment by jonyeezs** [comment]
This would be awesome like visual studios's tab `Installed` and `Updates`

**Comment by SaleCar** [comment]
I also agree that this would be good to have

**Comment by HanMoeHtet** [comment]
This is a major disappointment in .NET development. Microsoft built several GUI apps but not the essential GUI app all .NET developers need.

**Comment by Gruski** [comment]
I don't get how to use this if you can't see what's installed. How do you remove packages and see what versions you have?

**Comment by thunder6230** [comment]
there is another nuget manager and it is able to do that, however i like this one better since it is like in other ide's.

**Comment by pcislo** [comment]
I've added it in version 1.2.0.

**Comment by thunder6230** [comment]
And how can we see only the installed nugets? 🙂

**Comment by pcislo** [comment]
Use the `Installed` tab
![installed_packages](https://github.com/user-attachments/assets/c03b161d-9691-4004-a07e-2e799f956ea9)

**Comment by thunder6230** [comment]
![image](https://github.com/user-attachments/assets/d85d6b6f-6438-46b8-ae1e-e15b6f53fbfe)
Any idea? 
I am in a workflow with 2 folders as frontend and backend. can this be an issue?

**Comment by thunder6230** [comment]
Is there a future possibility to mark the items that have update or maybe a  3rd tab?

**Comment by pcislo** [comment]
> Is there a future possibility to mark the items that have update or maybe a 3rd tab?

Yes, I will add it in the next release.
