### ISSUE TITLE
How to open the gallery window?

### ISSUE THREAD

**Issue by uberubert** [pcislo/vscode-nuget-gallery#59]
The features page is a gif that shows the window randomly popping open. How would I reach this window and why is this not mentioned anywhere?

**Comment by pcislo** [comment]
If you take a look at this gif, you will see that gallery is opened through `Command Palette` with command "NuGet: Open NuGet Gallery"

**Comment by uberubert** [comment]
Well that's the problem then; I have no idea what the command palette is or how to reach it. 

Thanks for the answer, at least it cleared it up for me. However:

The documentation does not mention "Command palette". The first second of the gif rushes into this command palette and assumes I have knowledge of what this is and how to reach it. I do not.

I've used VsCode for over a year, actively, and I've never heard of or tried to access the command palette before. Whatever usage I've had of a input thingy near the top of VsCode has been the occational popup from other actions and never from me actively activating it to write anything. I suspect I'm not alone in this. A small instruction could be added to the readme or somewhere suitable, so unaware people like me who won't be so lost.

Something like this;

## How to use:
- Press `CTRL + p` in VsCode to open the `Command palette`
- Type `> NuGet: Open Nuget Gallery`
- Click the choice, the Nuget Gallery window should open
