### ISSUE TITLE
Trouble installing package in wsl environment

### ISSUE THREAD

**Issue by b3hniya** [pcislo/vscode-nuget-gallery#83]
I created a project in the ubuntu directory ( wsl ), and I wanted to add some packages using the nugget gallery extension, and I've got an error as below: 
Unable to create dependency graph file for project **'//wsl.localhost/Ubuntu/home/b3hniya/ProjectA/ProjectA.csproj'**. Cannot add package reference.

I looked at the command generated by the extension, and I've found this:
dotnet add **//wsl.localhost/Ubuntu/home/b3hniya/ProjectA/ProjectA.csproj** package Moq -v 4.18.1 -s https://api.nuget.org/v3/index.json

I changed the full path to the relative path, and it worked.
dotnet add **./.** Moq -v 4.18.1 -s https://api.nuget.org/v3/index.json

I tested the extension ( with wsl ) in a project located in the c directory, and it worked fine. It looks that the dotnet CLI has a problem with the full path on wsl ubuntu directories but works fine with relative paths.

**Comment by jonyeezs** [comment]
It seem to work for me

> Executing task: dotnet add /home/jonyee/dev/ellume/services/ec-ops-api/src/Ellume.Cloud.Ops.Api.Database/Ellume.Cloud.Ops.Api.Database.csproj package Marten.CommandLine -v 6.0.1 -s https://api.nuget.org/v3/index.json 
>  Determining projects to restore...
>  Writing /tmp/tmpj7435O.tmp
> info : Adding PackageReference for package 'Marten.CommandLine' into project '/home/jonyee/dev/ellume/services/ec-ops-api/src/Ellume.Cloud.Ops.Api.Database/Ellume.Cloud.Ops.Api.Database.csproj'.

I'd recommend checking your extension to see if it is installed in ubuntu
![image](https://github.com/pcislo/vscode-nuget-gallery/assets/10862726/f3a16073-f6c2-4376-9434-7bf6c5b6c7ae)


And that you're running VSCode through remote WSL (https://code.visualstudio.com/docs/remote/wsl)

These steps are crucial:

> 2. Install [Visual Studio Code](https://code.visualstudio.com/) on the Windows side (not in WSL).
>>    Note: When prompted to Select Additional Tasks during installation, be sure to check the Add to PATH option so you can easily open a folder in WSL using the code command.
> 3. Install the [WSL extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl). If you plan to work with other remote extensions in VS Code, you may choose to install the [Remote Development extension pack](https://aka.ms/vscode-remote/download/extension).
