### ISSUE TITLE
install not available?

### ISSUE THREAD

**Issue by Denver80211** [pcislo/vscode-nuget-gallery#85]
In VSCode, I have the extension installed and it's produced a list of all the installable packages.  I get the drop down for the version, etc
But the install button is not active on any package.  I can't click on install for any product as far as I can tell.  Running the latest vscode, 1.67.2, just installed your extension.  I tried running as administrator for kicks.. no luck.  Not sure what I'm missing
quick update.. I see from other closed issues "check the box next to project" -I don't get a list of projects?   I'm trying to use a package (extension?) with powershell so..  perhaps that's related?  I should be able to reference a package once installed.  Are you assuming we're only editing c# stuff or...?

**Comment by pcislo** [comment]
Hi, packages can only be installed in C# or F# projects.

**Comment by Denver80211** [comment]
OK.. that's too bad we use nuget packages frequently with powershell (c# based)
Thanks
