### ISSUE TITLE
Github package sources

### ISSUE THREAD

**Issue by bsaranga** [pcislo/vscode-nuget-gallery#89]
How do I configure a Github package source?

I have tried the following two options:

1.` {"name": "github", "url": "https://nuget.pkg.github.com/bsaranga/index.json", "packageSourceCredentials": { "username": "username", "clearTextPassword": "pw"}}`
2. `{"name": "github", "url": "https://nuget.pkg.github.com/bsaranga/index.json", "authorizationHeader": "Basic _"}`

Both doesn't seem to work.

**Comment by pcislo** [comment]
For authentication purposes, Credential Provider should be used. Make sure it's located in the folder, that was defined in setttings.

**Comment by jobou363** [comment]
Hi, i also have some problems with the configuration of Credential Provider with this king of config : 

{"name": "My Secure Feed","url": "https://nuget.sample.com/"}

Is there a simple way to use credential provider? I have tried bunch of things but cannot get it work.

I get this error message that is probably related to my source config. Is there a more detail message somewhere. Nothing is shown in the console log.

![image](https://user-images.githubusercontent.com/240580/199844894-88b7c4bf-2b5f-4327-90ee-cd6c4407120e.png)

**Comment by Snechko** [comment]
Hi, I'm also having trouble adding packages from private sources. I installed the credential provider in the right folder and added endpoints for it as environment variables: 

` {"endpointCredentials": [{"endpoint":"http://example.index.json", "username":"optional", "password":"accesstoken"}]}`

However, it is unclear if I should then add the source inside the extension settings.

![image](https://user-images.githubusercontent.com/74240436/216333251-7cfb1755-6cc7-4206-bd90-33664553b423.png)


Can you please help with this issue?

**Comment by terryaney** [comment]
I had success doing the environment variable and also adding nuget gallery source.  I was hoping it would just use the credential manager and prompt for creds, but the only way I got it to work was using the environment variable you've described above.

**Comment by alvahtin** [comment]
How can I make this work for gthub? I set the environment variable VSS_NUGET_EXTERNAL_FEED_ENDPOINTS="{\"endpointCredentials\": [\"endpoint\":\"https://nuget.pkg.github.com/MY_NAMESPACE/index.json\", {\"username\":\"MY_USER_NAME\", \"password\":\"MY_PAT\"}]}" 

But it doesn't work ((

**Comment by pcislo** [comment]
The new version should have fixed it. Let me know if any help is still needed here.

**Comment by goors** [comment]
Same here. I have VSS_NUGET_EXTERNAL_FEED_ENDPOINTS but when feed is selected it shows not packages.
