### ISSUE TITLE
Private package sources not picked up

### ISSUE THREAD

**Issue by joeapinder** [pcislo/vscode-nuget-gallery#9]
We use private nuget package sources, we have a local nuget.config file with those nuget repo locations in, but when I search for nuget packages in the nuget gallery extension it doesnt return anything, it looks like its not looking in those private package sources, do this tool support alternative package sources?

**Comment by pcislo** [comment]
Private package sources are not supported yet. I will add it in the next release.

**Comment by pcislo** [comment]
added feature request #10

**Comment by joeapinder** [comment]
> Private package sources are not supported yet. I will add it in the next release.

Great, thanks when is the next planned release?

**Comment by pcislo** [comment]
> 
> 
> > Private package sources are not supported yet. I will add it in the next release.
> 
> Great, thanks when is the next planned release?

It's hard to say, but I will try to add this feature within two weeks.
