### ISSUE TITLE
Nuget private

### ISSUE THREAD

**Issue by RiveraHan** [pcislo/vscode-nuget-gallery#90]
### Add nuget private
Hello, how can I add a private nuget?

**Comment by RiveraHan** [comment]
Added a user and password but it does not update or download the packages

![image](https://user-images.githubusercontent.com/55303043/191058340-70166641-a849-43f8-aa7e-588b19ab1942.png)

**Comment by pcislo** [comment]
For authentication purposes, Credential Provider should be used. Make sure it's located in the folder, that was defined in setttings.
