### ISSUE TITLE
error, Service not available

### ISSUE THREAD

**Issue by dodu2014** [pcislo/vscode-nuget-gallery#91]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/15245544/193778775-09160029-4e9c-472f-a0b2-16c104586ca7.png">

**Comment by sunnythynk** [comment]
I'm also getting this error very often. Restarting VS Code does fix this but I have to restart my system. Please resolve this issue.

**Comment by dodu2014** [comment]
ok, thanks
